# make sure to replace "my-repo" in the fluentd image with your repo name

apiVersion: apps/v1
kind: Deployment
metadata:
  name: iis-2019-with-logging
  labels:
    app: iis-2019-with-logging
spec:
  replicas: 1
  template:
    metadata:
      name: iis-2019-with-logging
      labels:
        app: iis-2019-with-logging
    spec:
  containers:
  - name: iis
    image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019
    resources:
      limits:
        cpu: 1
        memory: 800m
      requests:
        cpu: .1
        memory: 300m
    ports:
      - containerPort: 80
    volumeMounts:
    - mountPath: C:\inetpub\logs\LogFiles\w3svc1
      name: log-volume
  - name: fluentd
    image: {repo}/fluentd-win:1.3
    imagePullPolicy: Always
    volumeMounts:
    - mountPath: C:\logs
      name: log-volume
  volumes:
  - name: log-volume
    emptyDir: {}
      nodeSelector:
        "beta.kubernetes.io/os": windows
  selector:
    matchLabels:
      app: iis-2019-with-logging
---
apiVersion: v1
kind: Service
metadata:
  name: iis-with-logging
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: iis-2019-with-logging